FROM quay.io/feedyard/circleci-remote-docker:5.3.0

LABEL maintainers = "nic.cheneweth@thoughtworks.com"

# bin versions installed
ENV CC_TEST_REPORTER_VERSION=0.7.0

# general packages to support building infra oriented docker images
RUN apk --no-cache add  \
        curl \
        python3 \
        build-base \
        python3-dev \
        libffi-dev \
        libressl-dev \
        g++ \
        gcc \
        make && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    rm -r /root/.cache && \
    pip install \
        setuptools \
        wheel \
        twine \
        pipenv \
        pylint \
        pytest \
        pytest-runner \
        coverage \
        cryptography && \
    curl -SLO https://codeclimate.com/downloads/test-reporter/test-reporter-${CC_TEST_REPORTER_VERSION}-linux-amd64 && \
    mv test-reporter-${CC_TEST_REPORTER_VERSION}-linux-amd64 /usr/bin/cc-test-reporter && \
    chmod +x /usr/bin/cc-test-reporter

HEALTHCHECK NONE
