---
version: 2.1

orbs:
  executor-tools: feedyard/executor-tools@0.3.0
  common: feedyard/common-pipeline-tasks@0.6.0

workflows:
  version: 2

  circleci-python-pkg-agent-executor-pipeline:
    jobs:
      - executor-tools/dev-release:
          name: dev-release
          context: executor-publishing
          image: feedyard/circleci-python-pkg-agent
          registry: quay.io
          after-build:
            - run:
                name: configuration testing
                command: |
                  set -euo pipefail
                  inspec exec --no-distinct-exit --chef-license accept-silent profiles/cis-docker
                  CID="$(docker run -it -d --entrypoint ash quay.io/feedyard/circleci-python-pkg-agent:dev.$CIRCLE_SHA1)"
                  inspec exec profiles/circleci-python-pkg-agent/ -t docker://$CID --chef-license accept-silent
                  docker rm -f $CID
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
      - executor-tools/publish:
          context: executor-publishing
          image: feedyard/circleci-python-pkg-agent
          registry: quay.io
          after-publish:
            - common/slack:
                title: New Executor Version
                message: new version published feedyard/circleci-python-pkg-agent $CIRCLE_TAG
                webhook: SLACK_WEBHOOK
          clean-tags:
            - executor-tools/clean-quay:
                image: feedyard/circleci-python-pkg-agent
                bearer-token: QUAYIO_BEARER_TOKEN
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

  # builds nightly from .unpinned Dockerfile in order to always be a latest for base image and packages
  circleci-python-agent-executor-nightly-build:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - executor-tools/dev-release:
          name: nightly-build
          context: executor-publishing
          image: feedyard/circleci-python-pkg-agent
          dockerfile: Dockerfile.unpinned
          tag: nightly
          registry: quay.io
          after-build:
            - run:
                name: configuration testing
                command: |
                  set -euo pipefail
                  inspec exec --no-distinct-exit --chef-license accept-silent profiles/cis-docker
                  CID="$(docker run -it -d --entrypoint ash quay.io/feedyard/circleci-python-pkg-agent:nightly)"
                  inspec exec profiles/circleci-python-pkg-agent-unpinned/ -t docker://$CID --chef-license accept-silent
                  docker rm -f $CID
